const data = {
  id: 'instance_concept_node_shaoxing_integrated_circuit_industry',
  chainId: null,
  parentId: null,
  level: null,
  path: null,
  name: '集成电路',
  description: null,
  isLeaf: null,
  type: 0,
  nodeStatus: null,
  fusion: 60.46,
  localizationRate: null,
  contributionRate: null,
  innovationFlag: false,
  topCompanyCount: null,
  companyCount: null,
  chainIndustryType: null,
  expertCount: null,
  topExpertExist: false,
  loan: null,
  financing: null,
  financingSuccess: false,
  childList: [
    {
      id: 'instance_concept_node_shaoxing_integrated_circuit_industry-01',
      chainId: null,
      parentId: 'instance_concept_node_shaoxing_integrated_circuit_industry',
      level: null,
      path: null,
      name: '上游',
      description: null,
      isLeaf: null,
      type: 0,
      nodeStatus: null,
      fusion: 61.3,
      localizationRate: null,
      contributionRate: null,
      innovationFlag: false,
      topCompanyCount: null,
      companyCount: null,
      chainIndustryType: null,
      expertCount: null,
      topExpertExist: false,
      loan: null,
      financing: null,
      financingSuccess: false,
      childList: [
        {
          id: 'instance_concept_node_shaoxing_integrated_circuit_industry-0101',
          chainId: null,
          parentId:
            'instance_concept_node_shaoxing_integrated_circuit_industry-01',
          level: null,
          path: null,
          name: '集成电路设计',
          description: null,
          isLeaf: null,
          type: 0,
          nodeStatus: null,
          fusion: 49.37,
          localizationRate: null,
          contributionRate: null,
          innovationFlag: false,
          topCompanyCount: null,
          companyCount: null,
          chainIndustryType: '延链',
          expertCount: null,
          topExpertExist: false,
          loan: null,
          financing: null,
          financingSuccess: false,
          childList: [],
        },
        {
          id: 'instance_concept_node_shaoxing_integrated_circuit_industry-0102',
          chainId: null,
          parentId:
            'instance_concept_node_shaoxing_integrated_circuit_industry-01',
          level: null,
          path: null,
          name: '集成电路材料',
          description: null,
          isLeaf: null,
          type: 0,
          nodeStatus: null,
          fusion: 71.89,
          localizationRate: null,
          contributionRate: null,
          innovationFlag: false,
          topCompanyCount: null,
          companyCount: null,
          chainIndustryType: '延链',
          expertCount: null,
          topExpertExist: false,
          loan: null,
          financing: null,
          financingSuccess: false,
          childList: [],
        },
        {
          id: 'instance_concept_node_shaoxing_integrated_circuit_industry-0103',
          chainId: null,
          parentId:
            'instance_concept_node_shaoxing_integrated_circuit_industry-01',
          level: null,
          path: null,
          name: '集成电路设备',
          description: null,
          isLeaf: null,
          type: 0,
          nodeStatus: null,
          fusion: 23.35,
          localizationRate: null,
          contributionRate: null,
          innovationFlag: false,
          topCompanyCount: null,
          companyCount: null,
          chainIndustryType: null,
          expertCount: null,
          topExpertExist: false,
          loan: null,
          financing: null,
          financingSuccess: false,
          childList: [],
        },
      ],
    },
    {
      id: 'instance_concept_node_shaoxing_integrated_circuit_industry-02',
      chainId: null,
      parentId: 'instance_concept_node_shaoxing_integrated_circuit_industry',
      level: null,
      path: null,
      name: '中游',
      description: null,
      isLeaf: null,
      type: 0,
      nodeStatus: null,
      fusion: 12.74,
      localizationRate: null,
      contributionRate: null,
      innovationFlag: false,
      topCompanyCount: null,
      companyCount: null,
      chainIndustryType: null,
      expertCount: null,
      topExpertExist: false,
      loan: null,
      financing: null,
      financingSuccess: false,
      childList: [
        {
          id: 'instance_concept_node_shaoxing_integrated_circuit_industry-0201',
          chainId: null,
          parentId:
            'instance_concept_node_shaoxing_integrated_circuit_industry-02',
          level: null,
          path: null,
          name: '集成电路制造',
          description: null,
          isLeaf: null,
          type: 0,
          nodeStatus: null,
          fusion: 25.49,
          localizationRate: null,
          contributionRate: null,
          innovationFlag: false,
          topCompanyCount: null,
          companyCount: null,
          chainIndustryType: '延链',
          expertCount: null,
          topExpertExist: false,
          loan: null,
          financing: null,
          financingSuccess: false,
          childList: [],
        },
      ],
    },
    {
      id: 'instance_concept_node_shaoxing_integrated_circuit_industry-03',
      chainId: null,
      parentId: 'instance_concept_node_shaoxing_integrated_circuit_industry',
      level: null,
      path: null,
      name: '下游',
      description: null,
      isLeaf: null,
      type: 0,
      nodeStatus: null,
      fusion: 22.55,
      localizationRate: null,
      contributionRate: null,
      innovationFlag: false,
      topCompanyCount: null,
      companyCount: null,
      chainIndustryType: null,
      expertCount: null,
      topExpertExist: false,
      loan: null,
      financing: null,
      financingSuccess: false,
      childList: [
        {
          id: 'instance_concept_node_shaoxing_integrated_circuit_industry-0301',
          chainId: null,
          parentId:
            'instance_concept_node_shaoxing_integrated_circuit_industry-03',
          level: null,
          path: null,
          name: '集成电路封装测试',
          description: null,
          isLeaf: null,
          type: 0,
          nodeStatus: null,
          fusion: 45.1,
          localizationRate: null,
          contributionRate: null,
          innovationFlag: false,
          topCompanyCount: null,
          companyCount: null,
          chainIndustryType: null,
          expertCount: null,
          topExpertExist: false,
          loan: null,
          financing: null,
          financingSuccess: false,
          childList: [],
        },
      ],
    },
  ],
};

export { data };
