const data = {
  id: 'instance_concept_node_shaoxing_integrated_circuit_industry',
  chainId: null,
  parentId: null,
  level: null,
  path: null,
  name: '集成电路',
  description: null,
  isLeaf: null,
  type: 0,
  nodeStatus: null,
  fusion: 60.46,
  localizationRate: null,
  contributionRate: null,
  innovationFlag: false,
  topCompanyCount: null,
  companyCount: null,
  chainIndustryType: null,
  expertCount: null,
  topExpertExist: false,
  loan: null,
  financing: null,
  financingSuccess: false,
  childList: [
    {
      id: 'instance_concept_node_shaoxing_integrated_circuit_industry-01',
      chainId: null,
      parentId: 'instance_concept_node_shaoxing_integrated_circuit_industry',
      level: null,
      path: null,
      name: '上游',
      description: null,
      isLeaf: null,
      type: 0,
      nodeStatus: null,
      fusion: 61.3,
      localizationRate: null,
      contributionRate: null,
      innovationFlag: false,
      topCompanyCount: null,
      companyCount: null,
      chainIndustryType: null,
      expertCount: null,
      topExpertExist: false,
      loan: null,
      financing: null,
      financingSuccess: false,
      childList: [],
    },
    {
      id: 'instance_concept_node_shaoxing_integrated_circuit_industry-02',
      chainId: null,
      parentId: 'instance_concept_node_shaoxing_integrated_circuit_industry',
      level: null,
      path: null,
      name: '中游',
      description: null,
      isLeaf: null,
      type: 0,
      nodeStatus: null,
      fusion: 12.74,
      localizationRate: null,
      contributionRate: null,
      innovationFlag: false,
      topCompanyCount: null,
      companyCount: null,
      chainIndustryType: null,
      expertCount: null,
      topExpertExist: false,
      loan: null,
      financing: null,
      financingSuccess: false,
      childList: [],
    },
    {
      id: 'instance_concept_node_shaoxing_integrated_circuit_industry-03',
      chainId: null,
      parentId: 'instance_concept_node_shaoxing_integrated_circuit_industry',
      level: null,
      path: null,
      name: '下游',
      description: null,
      isLeaf: null,
      type: 0,
      nodeStatus: null,
      fusion: 22.55,
      localizationRate: null,
      contributionRate: null,
      innovationFlag: false,
      topCompanyCount: null,
      companyCount: null,
      chainIndustryType: null,
      expertCount: null,
      topExpertExist: false,
      loan: null,
      financing: null,
      financingSuccess: false,
      childList: [],
    },
    {
      id: 'instance_concept_node_shaoxing_integrated_circuit_industry-04',
      chainId: null,
      parentId: 'instance_concept_node_shaoxing_integrated_circuit_industry',
      level: null,
      path: null,
      name: '下下游',
      description: null,
      isLeaf: null,
      type: 0,
      nodeStatus: null,
      fusion: 22.55,
      localizationRate: null,
      contributionRate: null,
      innovationFlag: false,
      topCompanyCount: null,
      companyCount: null,
      chainIndustryType: null,
      expertCount: null,
      topExpertExist: false,
      loan: null,
      financing: null,
      financingSuccess: false,
      childList: [],
    },
  ],
};

export { data };
